name: Compilar APK con Buildozer

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    #Usamos la ruta real y actualizada del contenedor oficial de Buildozer
    - name: Compilar APK con Buildozer Action
      uses: subzero-io/buildozer-action@v1
      with:
        command: buildozer android debug
        repository_root: .

    - name: Guardar y subir el APK como resultado
      uses: actions/upload-artifact@v4
      with:
        name: Aplicacion-Pinguino-Android
        path: bin/*.apk